import type { ListingRow, Matter } from "@/lib/types";

const now = "2026-08-21 09:00";

function isoDays(offset: number) {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  return `${dd}/${mm}/${d.getFullYear()}`;
}

function iso(offset: number) {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return d.toISOString().slice(0, 10);
}

export const SAMPLE_MATTERS: Matter[] = [
  {
    id: "2|R|560|1842|2024",
    side: "2",
    side_label: "Original Side",
    stampreg: "R",
    stampreg_label: "Register",
    case_type: "560",
    type_name: "WP - WRIT PETITION",
    case_no: "1842",
    year: "2024",
    petitioner: "Meridian Logistics Pvt. Ltd.",
    respondent: "State of Maharashtra & Ors.",
    cnr: "HCBM020184212024",
    filed_on: "12/02/2024",
    registration_date: "18/02/2024",
    status: "Pending",
    disposal_date: "",
    lodging: "WPL/4412/2024",
    petitioner_adv: "Bharucha & Partners",
    respondent_adv: "Government Pleader",
    stage: "Admission",
    act: "Constitution of India",
    partner: "N. Dahiya",
    associates: "A. Shah",
    next_hearing: isoDays(0),
    next_listing: isoDays(0),
    last_listing: isoDays(-21),
    last_coram: "Hon'ble Shri Justice G. S. Patel",
    hearing_notes: [
      {
        id: "n1",
        text: "Court indicated it will hear the stay application with the connected notice of motion. File the additional affidavit of the transport commissioner before the next date.",
        date: iso(-21),
        createdAt: now,
      },
    ],
    next_steps: [
      {
        id: "t1",
        text: "File additional affidavit of the Transport Commissioner",
        done: false,
        due: iso(0),
      },
      {
        id: "t2",
        text: "Serve convenience compilation on GP by 4 pm",
        done: false,
        due: iso(0),
      },
    ],
    tags: ["board today"],
    order_count: 4,
    orders: [
      {
        key: "12/02/2024|Notice",
        srl: "4",
        date: "12/02/2024",
        doc: "Notice",
        coram: "Hon'ble Shri Justice G. S. Patel",
        downloaded: false,
      },
      {
        key: `${isoDays(-21)}|Interim Order`,
        srl: "1",
        date: isoDays(-21),
        doc: "Interim Order",
        coram: "Hon'ble Shri Justice G. S. Patel",
        downloaded: false,
        excerpt:
          "The petition is stood over. Petitioner to file the additional affidavit within two weeks. Ad-interim protection to continue till the next date of hearing.",
      },
    ],
    added_at: now,
    last_refresh: now,
    last_added: 0,
    sample: true,
  },
  {
    id: "2|R|742|88|2023",
    side: "2",
    side_label: "Original Side",
    stampreg: "R",
    stampreg_label: "Register",
    case_type: "742",
    type_name: "COMS - Commercial Suit",
    case_no: "88",
    year: "2023",
    petitioner: "Harbourline Shipping Ltd.",
    respondent: "Peninsula Ports Ltd.",
    cnr: "HCBM020008882023",
    filed_on: "04/03/2023",
    registration_date: "11/03/2023",
    status: "Pending",
    disposal_date: "",
    lodging: "",
    petitioner_adv: "Advani & Co.",
    respondent_adv: "Wadia Ghandy & Co.",
    stage: "Evidence",
    act: "Commercial Courts Act",
    partner: "N. Dahiya",
    associates: "M. Iyer, R. Kapoor",
    next_hearing: isoDays(1),
    next_listing: isoDays(1),
    last_listing: isoDays(-14),
    last_coram: "Hon'ble Smt. Justice Bharati Dangre",
    hearing_notes: [
      {
        id: "n2",
        text: "Cross of PW-1 part-heard. Mark the remaining invoices (Ex. P-14 onwards) and keep the original bills of lading ready.",
        date: iso(-14),
        createdAt: now,
      },
    ],
    next_steps: [
      {
        id: "t3",
        text: "Paginate remaining invoices for PW-1 cross",
        done: false,
        due: iso(1),
      },
      {
        id: "t4",
        text: "Confirm witness is available at 11 am",
        done: true,
        due: iso(-1),
      },
    ],
    tags: ["commercial"],
    order_count: 9,
    orders: [
      {
        key: `${isoDays(-14)}|Farad order`,
        srl: "1",
        date: isoDays(-14),
        doc: "Farad order",
        coram: "Hon'ble Smt. Justice Bharati Dangre",
        downloaded: false,
      },
    ],
    added_at: now,
    last_refresh: now,
    last_added: 0,
    sample: true,
  },
  {
    id: "2|R|743|15|2025",
    side: "2",
    side_label: "Original Side",
    stampreg: "R",
    stampreg_label: "Register",
    case_type: "743",
    type_name: "CARBP - Commercial Arbitration Petition",
    case_no: "15",
    year: "2025",
    petitioner: "Sterling Infra Projects LLP",
    respondent: "Western Grid Corporation",
    cnr: "HCBM020001552025",
    filed_on: "19/01/2025",
    registration_date: "22/01/2025",
    status: "Pending",
    disposal_date: "",
    lodging: "",
    petitioner_adv: "Bharucha & Partners",
    respondent_adv: "Cyril Amarchand Mangaldas",
    stage: "Section 9",
    act: "Arbitration and Conciliation Act",
    partner: "K. Mehta",
    associates: "A. Shah",
    next_hearing: isoDays(5),
    next_listing: isoDays(5),
    last_listing: isoDays(-30),
    last_coram: "Hon'ble Shri Justice B. P. Colabawalla",
    hearing_notes: [],
    next_steps: [
      {
        id: "t5",
        text: "Update note on bank guarantee invocation",
        done: false,
        due: iso(3),
      },
    ],
    tags: ["arb"],
    order_count: 3,
    orders: [
      {
        key: `${isoDays(-30)}|Interim Order`,
        srl: "1",
        date: isoDays(-30),
        doc: "Interim Order",
        coram: "Hon'ble Shri Justice B. P. Colabawalla",
        downloaded: false,
        excerpt:
          "Status quo in respect of the two performance bank guarantees until the next date. Petitioner to serve the complete compilation on the respondent.",
      },
    ],
    added_at: now,
    last_refresh: now,
    last_added: 0,
    sample: true,
  },
  {
    id: "1|R|621|402|2022",
    side: "1",
    side_label: "Appellate Side",
    stampreg: "R",
    stampreg_label: "Register",
    case_type: "621",
    type_name: "ASWP - APPELLATE SIDE WRIT PETITION",
    case_no: "402",
    year: "2022",
    petitioner: "Smt. Leela Narayan",
    respondent: "Municipal Corporation of Greater Mumbai",
    cnr: "HCBM010040222022",
    filed_on: "08/06/2022",
    registration_date: "14/06/2022",
    status: "Disposed",
    disposal_date: isoDays(-40),
    lodging: "",
    petitioner_adv: "Advani Law LLP",
    respondent_adv: "MCGM Legal",
    stage: "Disposed",
    act: "MMC Act",
    partner: "K. Mehta",
    associates: "",
    next_hearing: "",
    next_listing: "",
    last_listing: isoDays(-40),
    last_coram: "Hon'ble the Chief Justice & Hon'ble Shri Justice M. S. Sonak",
    hearing_notes: [
      {
        id: "n3",
        text: "Rule made absolute in part. MCGM to re-hear the demolition notice within eight weeks. Collect certified copy.",
        date: iso(-40),
        createdAt: now,
      },
    ],
    next_steps: [
      {
        id: "t6",
        text: "Apply for certified copy of the judgment",
        done: false,
        due: iso(-10),
      },
    ],
    tags: ["disposed"],
    order_count: 6,
    orders: [
      {
        key: `${isoDays(-40)}|Judgment`,
        srl: "1",
        date: isoDays(-40),
        doc: "Judgment",
        coram: "Hon'ble the Chief Justice",
        downloaded: false,
      },
    ],
    added_at: now,
    last_refresh: now,
    last_added: 0,
    sample: true,
  },
];

export function sampleListings(): ListingRow[] {
  const t = new Date();
  const tom = new Date();
  tom.setDate(t.getDate() + 1);
  const fmt = (d: Date) => ({
    short: `${d.getDate()} ${d.toLocaleDateString("en", { month: "short" })}`,
    full: `${d.getDate()} ${d.toLocaleDateString("en", { month: "long" })} ${d.getFullYear()}`,
    ddmm: `${String(d.getDate()).padStart(2, "0")}-${String(d.getMonth() + 1).padStart(2, "0")}-${d.getFullYear()}`,
  });
  const today = fmt(t);
  const tomorrow = fmt(tom);
  return [
    {
      date: today.short,
      date_full: today.full,
      date_ddmm: today.ddmm,
      matter: "Meridian Logistics Pvt. Ltd. v State of Maharashtra & Ors.",
      number: "WP/1842/2024",
      serial: "12",
      list_type: "Daily Board",
      judge: "Hon'ble Shri Justice G. S. Patel",
      court: "13",
      caption: "FOR ADMISSION",
      connected: "IA/2201/2024",
      reasons: ["Your matter"],
      tracked: true,
      mid: "2|R|560|1842|2024",
      add: null,
    },
    {
      date: tomorrow.short,
      date_full: tomorrow.full,
      date_ddmm: tomorrow.ddmm,
      matter: "Harbourline Shipping Ltd. v Peninsula Ports Ltd.",
      number: "COMS/88/2023",
      serial: "4",
      list_type: "Daily Board",
      judge: "Hon'ble Smt. Justice Bharati Dangre",
      court: "18",
      caption: "FOR EVIDENCE",
      connected: "",
      reasons: ["Your matter"],
      tracked: true,
      mid: "2|R|742|88|2023",
      add: null,
    },
    {
      date: tomorrow.short,
      date_full: tomorrow.full,
      date_ddmm: tomorrow.ddmm,
      matter: "Aarav Textiles v Union of India",
      number: "WP/991/2025",
      serial: "31",
      list_type: "Daily Board",
      judge: "Hon'ble Shri Justice G. S. Patel",
      court: "13",
      caption: "FOR ADMISSION",
      connected: "",
      reasons: ["Bharucha & Partners"],
      tracked: false,
      mid: null,
      add: { abbr: "WP", stampreg: "R", no: "991", year: "2025" },
    },
  ];
}
